// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
public class diezTests {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    String so = System.getProperty("so");
    System.out.println("---- Running with so " + so + "----");

    if (so.equals("linux")){
      System.setProperty("webdriver.chrome.driver","drivers/chromedriver_linux");
    }
    if (so.equals("windows")){
      System.setProperty("webdriver.chrome.driver","drivers/chromedriver_windows.exe");
    }
    if (so.equals("mac")){
      System.setProperty("webdriver.chrome.driver","drivers/chromedriver");
    }
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    try {
      Thread.sleep(2000);
    } catch (InterruptedException e) {e.printStackTrace();}
    driver.quit();
  }

  @Test
  public void diez() {
    driver.get("http://localhost:8000/");
    driver.manage().window().setSize(new Dimension(1920, 1080));
    driver.findElement(By.cssSelector("body")).click();
    driver.findElement(By.linkText("Retiro 10%")).click();
    driver.findElement(By.id("id_ahorro")).click();
    driver.findElement(By.id("id_ahorro")).sendKeys("30000000");
    driver.findElement(By.id("id_sueldo")).sendKeys("10000000");
    driver.findElement(By.cssSelector("div > div:nth-child(1)")).click();
    driver.findElement(By.cssSelector("input:nth-child(1)")).click();
    driver.findElement(By.cssSelector("div > div:nth-child(1)")).click();
  }
}
